long_term_care_10_intro = {
	# "session['course']": "life-health-course-4",
	"title": "Long-term-care: Introduction",
	"course": "Florida 10-Hour Long-Term Care & Partnership Programs",
	"course_number": "113776",
	"hours_approved": "10  Health Agent Electives (2-40)",
	"price": "$19.00",

	"tagline": "This course fulfills the state-mandated requirements for the Health Agent Electives continuing education component for Florida-licensed agents.(2-40)",
	"summary": "This course covers the nature of long-term care, available long-term care services and providers,\
	long-term care insurance products, government-sponsored health care options,\
	partnership programs, alternative LTC funding options, and the ethical and suitability issues associated\
	with long-term care products and policies.",


	"highlight": {
		1: 'Conditions that have led to the growing need for long-term care',
		2: 'Elder Care Needs',
		3: 'Types of long-term care providers and the services they offer',
		4: 'Options and limitations of Medicare and Medicaid for paying for long-term care',
		5: 'Fundamentals of long-term care partnership programs and their requirements',
		}
	}

long_term_care_10_chapter_1 = {
	"title": "Long Term Care: Chapter 1",
	"course": "10-Hour Long-Term-Care & Partnershp Programs",
	"chapter_no": 1,
	"chapter_total":  11,
	"pdf": "/static/fl-life-health/course-2-image/chapter_1.pdf",
	"url_results": "health_course_2_chapter_1_results",
	"question_1":"A quality elder care plan will be concerned with what?",
	"answer_1a": "Amount of assets",
	"answer_1b": "Quality of life",
	"answer_1c": "Low deductibles",
	"answer_1d": "Years left to live",
	"value_1a": "",
	"value_1b": "correct",
	"value_1c": "",
	"value_1d": "",
	"question_2":"Which is not a factor that influences the risk of needing long-term care?",
	"answer_2a": "Gender",
	"answer_2b": "Marital Status",
	"answer_2c": "Height",
	"answer_2d": "Lifestyle",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "correct",
	"value_2d": "",
	"result_title": "Long-Term-Care: Chapter 1 Results",
	"answer_1": "Quality of life",
	"answer_2": "Height",
	"url_wrong": "health_course_2_chapter_1",
	"url_correct": "health_course_2_chapter_2",
	}

long_term_care_10_chapter_2 = {
	"title": "Long Term Care: Chapter 2",
	"course": "10-Hour Long-Term-Care & Partnershp Programs",
	"chapter_no": 2,
	"chapter_total":  11,
	"pdf": "/static/fl-life-health/course-2-image/chapter-2.pdf",
	"url_results": "health_course_2_chapter_2_results",
	"question_1":"Who has become the primary single payor of long-term care services?",
	"answer_1a": "Medicare",
	"answer_1b": "Social Security",
	"answer_1c": "Medicaid",
	"answer_1d": "Obamacare",
	"value_1a": "",
	"value_1b": "",
	"value_1c": "correct",
	"value_1d": "",
	"question_2":"What must happen in order for a LTC policy to be considered “tax-qualified”?",
	"answer_2a": "The policy must be guaranteed renewable",
	"answer_2b": "The policy must provide for a cash surrender value",
	"answer_2c": "It must be purchased from the IRS",
	"answer_2d": "The policy must have a “No-contest” clause",
	"value_2a": "correct",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "",
	"result_title": "Long-Term-Care: Chapter 2 Results",
	"answer_1": "Medicaid",
	"answer_2": "The policy must be guaranteed renewable",
	"url_wrong": "health_course_2_chapter_2",
	"url_correct": "health_course_2_chapter_3",
	}

long_term_care_10_chapter_3 = {
	"title": "Long Term Care: Chapter 3",
	"course": "10-Hour Long-Term-Care & Partnershp Programs",
	"chapter_no": 3,
	"chapter_total":  11,
	"pdf": "/static/fl-life-health/course-2-image/chapter-3.pdf",
	"url_results": "health_course_2_chapter_3_results",
	"question_1":"A comprehensive long-term care policy will include which?",
	"answer_1a": "Respite care for caregivers",
	"answer_1b": "Memory care centers",
	"answer_1c": "Skilled nursing facility care",
	"answer_1d": "All of the above",
	"value_1a": "",
	"value_1b": "",
	"value_1c": "",
	"value_1d": "correct",
	"question_2":"The premium for a long-term care policy is established when the policy is issued, and will:",
	"answer_2a": "Increase",
	"answer_2b": "Decrease",
	"answer_2c": "Multiply",
	"answer_2d": "Remain at the same level",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "correct",
	"result_title": "Long-Term-Care: Chapter 3 Results",
	"answer_1": "All of the above",
	"answer_2": "Remain at the same level",
	"url_wrong": "health_course_2_chapter_3",
	"url_correct": "health_course_2_chapter_4",
	}

long_term_care_10_chapter_4 = {
	"title": "Long Term Care: Chapter 4",
	"course": "10-Hour Long-Term-Care & Partnershp Programs",
	"chapter_no": 4,
	"chapter_total":  11,
	"pdf": "/static/fl-life-health/course-2-image/chapter-4.pdf",
	"url_results": "health_course_2_chapter_4_results",
	"question_1":"A Partnership Program joins a state’s Medicaid program with ownership of private LTC insurance in such \
	a way that the state’s_______ requirements are modified to provide financial incentives for residents to purchase private LTCI coverage.",
	"answer_1a": "Personal Property",
	"answer_1b": "Social Security eligibility",
	"answer_1c": "Medicaid eligibility",
	"answer_1d": "",
	"value_1a": "",
	"value_1b": "",
	"value_1c": "correct",
	"value_1d": "",
	"question_2":"Under this Partnership Program model, asset protection is equal to the amount \
	of benefits paid from the partnership policy?",
	"answer_2a": "Total Asset Protection",
	"answer_2b": "Dollar-for-Dollar",
	"answer_2c": "Social Security",
	"answer_2d": "Deductible Free",
	"value_2a": "",
	"value_2b": "correct",
	"value_2c": "",
	"value_2d": "",
	"result_title": "Long-Term-Care: Chapter 4 Results",
	"answer_1": "Medicaid eligibility",
	"answer_2": "Dollar-for-Dollar",
	"url_wrong": "health_course_2_chapter_4",
	"url_correct": "health_course_2_chapter_5",
	}

long_term_care_10_chapter_5 = {
	"title": "Long Term Care: Chapter 5",
	"course": "10-Hour Long-Term-Care & Partnershp Programs",
	"chapter_no": 5,
	"chapter_total":  11,
	"pdf": "/static/fl-life-health/course-2-image/chapter-5.pdf",
	"url_results": "health_course_2_chapter_5_results",
	"question_1":"When was the Long-Term Care Partnership Program created?",
	"answer_1a": "late 1970s",
	"answer_1b": "late 1980s",
	"answer_1c": "late 2000s",
	"answer_1d": "late 1950s",
	"value_1a": "",
	"value_1b": "correct",
	"value_1c": "",
	"value_1d": "",
	"question_2":"Which one of these four states initially \
	implemented the Partnership Programs in the early 1990s?",
	"answer_2a": "New York",
	"answer_2b": "Nevada",
	"answer_2c": "Georgia",
	"answer_2d": "Florida",
	"value_2a": "correct",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "",
	"result_title": "Long-Term-Care: Chapter 5 Results",
	"answer_1": "late 1980s",
	"answer_2": "New York",
	"url_wrong": "health_course_2_chapter_5",
	"url_correct": "health_course_2_chapter_6",
	}

long_term_care_10_chapter_6 = {
	"title": "Long Term Care: Chapter 6",
	"course": "10-Hour Long-Term-Care & Partnershp Programs",
	"chapter_no": 6,
	"chapter_total":  11,
	"pdf": "/static/fl-life-health/course-2-image/chapter-6.pdf",
	"url_results": "health_course_2_chapter_6_results",
	"question_1":"Which is not a goal of Long-Term Care Insurance Model Act?",
	"answer_1a": "To promote the availability of long-term care insurance coverage",
	"answer_1b": "To facilitate public understanding and comparison of long-term care insurance coverages",
	"answer_1c": "To promote the public interest",
	"answer_1d": "To increase exposure to the states",
	"value_1a": "",
	"value_1b": "",
	"value_1c": "",
	"value_1d": "correct",
	"question_2":"Long-Term Care Partnership policies must be issued as:",
	"answer_2a": "High Deductible",
	"answer_2b": "Low Deductible",
	"answer_2c": "Guaranteed Renewable",
	"answer_2d": "No Co-Pay",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "correct",
	"value_2d": "",
	"result_title": "Long-Term-Care: Chapter 6 Results",
	"answer_1": "To increase exposure to the states",
	"answer_2": "Guaranteed Renewable",
	"url_wrong": "health_course_2_chapter_6",
	"url_correct": "health_course_2_chapter_7",
	}

long_term_care_10_chapter_7 = {
	"title": "Long Term Care: Chapter 7",
	"course": "10-Hour Long-Term-Care & Partnershp Programs",
	"chapter_no": 7,
	"chapter_total":  11,
	"pdf": "/static/fl-life-health/course-2-image/chapter-7.pdf",
	"url_results": "health_course_2_chapter_7_results",
	"question_1":"What is not a reason to be excluded from a long-term care policy?",
	"answer_1a": "Mental or nervous disorders, except for Alzheimer's and other progressive, degenerative and dementing illnesses",
	"answer_1b": "Preexisting conditions, under certain circumstances",
	"answer_1c": "Alcoholism and drug addition",
	"answer_1d": "Illiterate",
	"value_1a": "",
	"value_1b": "",
	"value_1c": "",
	"value_1d": "correct",
	"question_2":"________ were created in 2003 so that individuals covered by high-deductible health plans could receive tax-preferred treatment of money saved for medical expenses.",
	"answer_2a": "Health Savings Accounts",
	"answer_2b": "Partnership Savings Accounts",
	"answer_2c": "Dollar-for-Dollar Savings Accounts",
	"answer_2d": "Health Insurance Accounts",
	"value_2a": "correct",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "",
	"result_title": "Long-Term-Care: Chapter 7 Results",
	"answer_1": "Illiterate",
	"answer_2": "Health Savings Accounts",
	"url_wrong": "health_course_2_chapter_7",
	"url_correct": "health_course_2_chapter_8",
	}

long_term_care_10_chapter_8 = {
	"title": "Long Term Care: Chapter 8",
	"course": "10-Hour Long-Term-Care & Partnershp Programs",
	"chapter_no": 8,
	"chapter_total":  11,
	"pdf": "/static/fl-life-health/course-2-image/chapter-8.pdf",
	"url_results": "health_course_2_chapter_8_results",
	"question_1":"Most Medicare Part D prescription drug plans have a gap in coverage that is called:",
	"answer_1a": "The ”loss of D”",
	"answer_1b": "The “donut hole”",
	"answer_1c": "The “coverage hole”",
	"answer_1d": "The “prescription zone”",
	"value_1a": "",
	"value_1b": "correct",
	"value_1c": "",
	"value_1d": "",
	"question_2":"Companies issuing long-term care policies allow a_____ period to do just that.  It is commonly called the 'free look' period.",
	"answer_2a": "60-day",
	"answer_2b": "7-day",
	"answer_2c": "30-day",
	"answer_2d": "99-day",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "correct",
	"value_2d": "",
	"result_title": "Long-Term-Care: Chapter 8 Results",
	"answer_1": "The “donut hole”",
	"answer_2": "30-day",
	"url_wrong": "health_course_2_chapter_8",
	"url_correct": "health_course_2_chapter_9",
	}

long_term_care_10_chapter_9 = {
	"title": "Long Term Care: Chapter 9",
	"course": "10-Hour Long-Term-Care & Partnershp Programs",
	"chapter_no": 9,
	"chapter_total":  11,
	"pdf": "/static/fl-life-health/course-2-image/chapter-9.pdf",
	"url_results": "health_course_2_chapter_9_results",
	"question_1":"Someone who is not a candidate for long-term care insurance:",
	"answer_1a": "Prefers to spare their family the responsibility for care",
	"answer_1b": "Is concerned about preserving assets for a spouse or heirs",
	"answer_1c": "Receives public assistance",
	"answer_1d": "Has a fair amount of assets to protect",
	"value_1a": "",
	"value_1b": "",
	"value_1c": "correct",
	"value_1d": "",
	"question_2":"Knowingly making any misleading representation or incomplete or fraudulent comparison of any insurance policy is called what?",
	"answer_2a": "Twisting",
	"answer_2b": "Defamation",
	"answer_2c": "Sliding",
	"answer_2d": "Suitability",
	"value_2a": "correct",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "",
	"result_title": "Long-Term-Care: Chapter 9 Results",
	"answer_1": "Receives public assistance",
	"answer_2": "Twisting",
	"url_wrong": "health_course_2_chapter_9",
	"url_correct": "health_course_2_chapter_10",
	}

long_term_care_10_chapter_10 = {
	"title": "Long Term Care: Chapter 10",
	"course": "10-Hour Long-Term-Care & Partnershp Programs",
	"chapter_no": 10,
	"chapter_total":  11,
	"pdf": "/static/fl-life-health/course-2-image/chapter-10.pdf",
	"url_results": "health_course_2_chapter_10_results",
	"question_1":"______ is community based group program that provides health, social and related support services in a facility that is licensed or certified by the state?",
	"answer_1a": "Nursing Home Care",
	"answer_1b": "Community Care",
	"answer_1c": "Premium Day Care",
	"answer_1d": "Adult Day Health Care",
	"value_1a": "",
	"value_1b": "",
	"value_1c": "",
	"value_1d": "correct",
	"question_2":"Companion care or live-in care provided by or through a home health care agency, to temporarily relieve the informal caregiver in the home convalescent unit is called?",
	"answer_2a": "Respite Care",
	"answer_2b": "Windowing",
	"answer_2c": "Community Care",
	"answer_2d": "Misrepresentation",
	"value_2a": "correct",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "",
	"result_title": "Long-Term-Care: Chapter 10 Results",
	"answer_1": "Adult Day Health Care",
	"answer_2": "Respite Care",
	"url_wrong": "health_course_2_chapter_10",
	"url_correct": "health_course_2_chapter_11",
	}

long_term_care_10_chapter_11 = {
	"title": "Long Term Care: Chapter 11",
	"course": "10-Hour Long-Term-Care & Partnershp Programs",
	"chapter_no": 11,
	"chapter_total":  11,
	"pdf": "/static/fl-life-health/course-2-image/chapter_11.pdf",
	"url_results": "health_course_2_chapter_11_results",
	"question_1":"Guidelines issued by an insurer that help consumers determine whether \
	a long-term care insurance policy is appropriate for them is called?",
	"answer_1a": "Agents Standards",
	"answer_1b": "Suitability Standards",
	"answer_1c": "Insurers Standards",
	"answer_1d": "Stakeholders Standards",
	"value_1a": "",
	"value_1b": "correct",
	"value_1c": "",
	"value_1d": "",
	"question_2":"A_____ waives the premium requirement once the insured begins to collect qualified policy benefits.",
	"answer_2a": "Insurance  Premium",
	"answer_2b": "Legal Team",
	"answer_2c": "Pre-existing Condition",
	"answer_2d": "Waiver of Premium",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "correct",
	"result_title": "Long-Term-Care: Chapter 11 Results",
	"answer_1": "Suitability Standards",
	"answer_2": "Waiver of Premium",
	"url_wrong": "health_course_2_chapter_11",
	"url_correct": "security_question",
	'url':'health_course_2_final_prep',
	'last_chapter':True,
	}

long_term_care_10_final_prep = {
	"title": "Florida Discount Continuing Education: Long Term Care Final Prep",
	"course": "10-Hour Long-Term-Care & Partnershp Programs",
	"url_final_exam":"health_course_2_final_exam",
	"url_review":"health_course_2_review",
	}

long_term_care_10_review = {
	"title": "Florida Discount Continuing Education: Long Term Care Review",
	"url_final_prep": "health_course_2_final_prep",
	"pdf": "/static/fl-life-health/course-2-image/full-course.pdf",
	}

long_term_care_10_final_exam = {
	"title": "Florida Discount Continuing Education: Long-Term-Care Final",
	"course": "10-Hour Long-Term-Care Update",
	"url_final_results": "health_course_2_final_results",

	"questions": {
		1: {'question': "By 2020, the number of Americans over the age of 65\
		 that require long-term-care service will increase to how many?",
		'answer_a': '1 million',
		'answer_b': '12 million',
		'answer_c': '2 million',
		'answer_d': '100,000',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': '',
		'value_d': 'w',
			},
		2: {'question': "Which degenerative disease is estimated to have an economic impact of $33 billion a year?",
		'answer_a': 'Leukemia',
		'answer_b': 'Muscular Dystrophy',
		'answer_c': 'Legionnaires Disease',
		'answer_d': 'Alzheimer’s Disease',
		'value_a': 'w',
		'value_b': '',
		'value_c': 'w',
		'value_d': 'correct',
			},
		3: {'question': "The number of days after which the policy holder qualifies for benefits, but before benefits are payable is called?",
		'answer_a': 'No-care period',
		'answer_b': 'U-pay period',
		'answer_c': 'Elimination period',
		'answer_d': 'Time to service',
		'value_a': 'w',
		'value_b': '',
		'value_c': 'correct',
		'value_d': 'w',
			},

		4: {'question': "What is not considered Instrumental Activities of Daily Living (IADLs)?",
		'answer_a': 'Toileting',
		'answer_b': 'Transferring',
		'answer_c': 'Shopping',
		'answer_d': 'Continence maintenance',
		'value_a': 'w',
		'value_b': '',
		'value_c': 'correct',
		'value_d': 'w',
			},

		5: {'question': "Most states require that policies covering long-term care services cannot contain a \
		pre-existing condition limitation of more than ______ after the effective date of coverage.",
		'answer_a': '3 months',
		'answer_b': '1 year',
		'answer_c': '5 years',
		'answer_d': '6 months',
		'value_a': 'w',
		'value_b': '',
		'value_c': 'w',
		'value_d': 'correct',
			},

		6: {'question': "What is the name given to a family member or friend who provides informal, unpaid care? ",
		'answer_a': 'Arbiter',
		'answer_b': 'Litigator',
		'answer_c': 'Nurse',
		'answer_d': 'Caregiver',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		7: {'question': "How old was thhe average age of early Partnership Program respondents?",
		'answer_a': '38 or 39 years old',
		'answer_b': '58 or 59 years old',
		'answer_c': '78 or 79 years old',
		'answer_d': '28 or 29 years old',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		8: {'question': "The Family and Medical Leave Act (FMLA), requires employers to grant up to_____ unpaid leave per year?",
		'answer_a': '12 weeks',
		'answer_b': '1 weeks',
		'answer_c': '4 weeks',
		'answer_d': '52 weeks',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		9: {'question': "The likelihood of receiving long-term care assistance increases with:",
		'answer_a': 'Height',
		'answer_b': 'Age',
		'answer_c': 'Wealth',
		'answer_d': 'Family Size',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		10: {'question': "An example of a Community-based service is?",
		'answer_a': 'Adult day service',
		'answer_b': 'Senior centers',
		'answer_c': 'Care-giver support programs',
		'answer_d': 'All of the above',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		11: {'question': "Which designates a person to make treatment decisions in the event that a patient cannot make decisions personally?",
		'answer_a': 'Advanced Directive',
		'answer_b': 'Non-Living Will',
		'answer_c': 'Living Will',
		'answer_d': 'Administrative Action',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		12: {'question': "What is not a factor that influences the risk of needing long-term care services?",
		'answer_a': 'Height',
		'answer_b': 'Lifestyle',
		'answer_c': 'Gender',
		'answer_d': 'Marital Status',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		13: {'question': "Where do most long-term care recipients receive their care?",
		'answer_a': 'Nursing Homes',
		'answer_b': 'Assisted Living Facilities',
		'answer_c': 'Home',
		'answer_d': 'Marital Status',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		14: {'question': "What will lead to a sharp growth in federal entitlement spending?",
		'answer_a': 'Lower tax polices',
		'answer_b': 'Capital gains tax',
		'answer_c': 'Aging baby boomers',
		'answer_d': 'Wealth inequality',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		15: {'question': "Which type of care primarily provides assistance with Activities of daily living (ADLs)?",
		'answer_a': 'Intermediate Care',
		'answer_b': 'Custodial Care',
		'answer_c': 'Skilled care',
		'answer_d': 'Foundation Care',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		16: {'question': "What is the medical term for moving into or out of a bed, chair, or wheelchair?",
		'answer_a': 'Transferring',
		'answer_b': 'Toileting',
		'answer_c': 'Translating',
		'answer_d': 'Transforming',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		17: {'question': "In what year were the Medicare and Medicaid programs created?",
		'answer_a': '1985',
		'answer_b': '1995',
		'answer_c': '1965',
		'answer_d': '1935',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		18: {'question': "Public financing for long-term-care services and support comes primarily from what program?",
		'answer_a': 'Medicaid',
		'answer_b': 'Medicare',
		'answer_c': 'Social Security',
		'answer_d': 'FMLA',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		19: {'question': "If certain conditions are met, Medicare will fully cover the first how many days of care in a skilled nursing facility (SNF) during each benefit period",
		'answer_a': '1 week',
		'answer_b': '1 month',
		'answer_c': '90 days',
		'answer_d': '20 days',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		20: {'question': "The first long-term care insurance policies were of one type.  Which one?",
		'answer_a': 'Home Based',
		'answer_b': 'Assisted Living',
		'answer_c': 'Nursing Home',
		'answer_d': 'Community Based',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		21: {'question': "Which is considered a countable-asset to Medicaid?",
		'answer_a': 'Automobile',
		'answer_b': 'Household belongings',
		'answer_c': 'Personal possesions',
		'answer_d': 'Checking and Savings accounts',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		22: {'question': "This type of long-term care policy is referred to as “Shared Care”?",
		'answer_a': 'Reimbursement benefit policies',
		'answer_b': 'Long-term benefit policies',
		'answer_c': 'Linked benefit policies',
		'answer_d': 'Shared benefit policies',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		23: {'question': "Which would Medicaid consider non-countable income?",
		'answer_a': 'Salaries and wages',
		'answer_b': 'Food stamps',
		'answer_c': 'Veterans’ benefits',
		'answer_d': 'Interest earnings and dividends',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		24: {'question': "This type of long term care is furnished by nurses, home aides, homemakers and other paid providers?",
		'answer_a': 'Driving care',
		'answer_b': 'Informal care',
		'answer_c': 'Friendly care',
		'answer_d': 'Formal care',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		25: {'question': "States are required to permit the community spouse of nursing facility residents to retain \
		income sufficient for support to protect them form spousal impoverishment.  What is this called?",
		'answer_a': 'Monthly Maintenance Allowance (MMA)',
		'answer_b': 'Minimum Money Maintenance Allowance (MMMA)',
		'answer_c': 'Money Needs Allowance (MNA)',
		'answer_d': 'Minimum Monthly Maintenance Needs Allowance (MMMNA)',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		26: {'question': "What is a risk of self funding long term care?",
		'answer_a': 'Not being able to define future long-term health-care needs',
		'answer_b': 'Not knowing when long-term care may be needed',
		'answer_c': 'Sacrificing money toward care that is intended to be passed on to family members and dependents',
		'answer_d': 'All of the above',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		27: {'question': "The policy’s_____ is the amount that the policy will pay, usually expressed as a dollar-per-day amount",
		'answer_a': 'Dollar-for-Dollar',
		'answer_b': 'Per Diem',
		'answer_c': 'Benefit Amount',
		'answer_d': 'Deductibles',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		28: {'question': "Which is not considered a Home Based Care service?",
		'answer_a': 'Homemaker services',
		'answer_b': 'Vallet services',
		'answer_c': 'Non-medical personal care',
		'answer_d': 'Home health care',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		29: {'question': "Long-term care contracts include a grace period of how many days before the policy lapses for nonpayment of premium?",
		'answer_a': '7',
		'answer_b': '14',
		'answer_c': '100',
		'answer_d': '31',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		30: {'question': "Self-funding of long-term care is possible for who?",
		'answer_a': 'Individuals with above-average wealth',
		'answer_b': 'People who can\'t afford it',
		'answer_c': 'Individuals over 65',
		'answer_d': 'Married couples',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		31: {'question': "A Partnership Program joins a state’s _____ program with ownership of private LTC insurance.",
		'answer_a': 'Social Security',
		'answer_b': 'Medicare',
		'answer_c': 'Welfare',
		'answer_d': 'Medicaid',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		32: {'question': "The Long-Term Care Partnership Program was developed in the late 1980's by who?",
		'answer_a': 'The Robert Frost Foundation',
		'answer_b': 'FEMA',
		'answer_c': 'The LTC Project',
		'answer_d': 'The Robert Wood Johnson Foundation',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		33: {'question': "What percent of people currently receiving long-term care are adults 18 to 64 years old.",
		'answer_a': '65 percent',
		'answer_b': '40 percent',
		'answer_c': '10 percent',
		'answer_d': '90 percent',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': '',
			},

		34: {'question': "Which of the following services would be paid by Medicare:",
		'answer_a': 'Custodial care',
		'answer_b': 'Medical Supplies',
		'answer_c': 'Lab tests',
		'answer_d': 'All of the above',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		35: {'question': " Which is not a requirement for an LTC policy to qualify for use in a state partnership program?",
		'answer_a': 'The policy holder must have assets over $100,000',
		'answer_b': 'The policy must meet the definition of a tax-qualified LTCI policy',
		'answer_c': 'The policy holder must be a resident of the partnership state when the policy is issued',
		'answer_d': 'The policy must include some measure of inflation protection for purchasers younger than 76 and the offer to purchase inflation protection for those who are 76 and older',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		36: {'question': "In which Partnership Program Model are all assets protected when a state-defined minimum benefit package is purchased by the consumer?",
		'answer_a': 'Total Asset Protection',
		'answer_b': 'Dollar-for-Dollar',
		'answer_c': 'Flood & Body',
		'answer_d': ' Dwelling & Property',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		37: {'question': "If an asset is improperly transferred, a state can consider the asset countable. States can “look back” how many months to find improper transfers of assets?",
		'answer_a': '6 months',
		'answer_b': '12 months',
		'answer_c': '60 months',
		'answer_d': '24 months',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		38: {'question': "What is not considered Activities of daily living (ADLs)?",
		'answer_a': 'Bathing',
		'answer_b': 'Driving',
		'answer_c': 'Eating',
		'answer_d': 'Dressing',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		39: {'question': "There are several ways that benefits may be reduced to save on premiums.  Which is not one of them?",
		'answer_a': 'Lower the deductible',
		'answer_b': 'Reduce the daily benefit amount',
		'answer_c': 'Reduce the length of benefit payments',
		'answer_d': 'Discontinue some benefits, such as home health care options',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		40: {'question': "What is an example of a deceptive trade practice or act?",
		'answer_a': 'Representing that consumer goods or services have a sponsorship, approval, use, or benefit that they do not have',
		'answer_b': 'The use of any plan or scheme in soliciting sales or services over the telephone that misrepresents the solicitor’s true status or mission',
		'answer_c': 'Disparaging the goods or services or business of another by a false or misleading representation of a material fact',
		'answer_d': 'All of the above',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		41: {'question': " What is it called when an agency misrepresents a material fact in selling or offering to sell a long-term care insurance policy?",
		'answer_a': 'Twisting',
		'answer_b': 'Defamation',
		'answer_c': 'Suitability',
		'answer_d': 'Misrepresentation',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		42: {'question': "What is the total amount the insurance company will pay during the insured's lifetime for all benefits covered by the policy?",
		'answer_a': 'Maximum Lifetime Benefit',
		'answer_b': 'Total Deductible',
		'answer_c': 'Endorsement Payback',
		'answer_d': 'Risk Benefit Amount',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		43: {'question': "This condition of  an individual requires frequent monitoring by medical professionals, such as physicians and registered nurses, in order to maintain the patient’s health status:",
		'answer_a': 'Re-action',
		'answer_b': 'Continence',
		'answer_c': 'Acute',
		'answer_d': 'Ambulation',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		44: {'question': "Of the total costs of long-term care services,how much are covered by private insurance?",
		'answer_a': 'Less than 1 percent',
		'answer_b': '5 percent',
		'answer_c': '20 percent',
		'answer_d': '50 percent',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		45: {'question': "The Robert Wood Johnson Foundation (RWJF) had specific goals when creating the Partnership Program, which is not one of them?",
		'answer_a': 'Assurance of equity and affordability in the long-term-care-insurance program for lower-income individuals',
		'answer_b': 'Assisting in raising deductibles along with inflation',
		'answer_c': 'Providing coverage for a full range of home and community-based services',
		'answer_d': 'Avoiding impoverishment for elderly individuals by guaranteeing some measure of asset protection',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		46: {'question': "Partnership Program long-term care policies offer three asset protection models.  Dollar-for-Dollar, Total Asset Protection, and what else?",
		'answer_a': 'Indemnity Model',
		'answer_b': 'Partner Model',
		'answer_c': 'Deductible Model',
		'answer_d': 'Hybrid Model',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		47: {'question': "Partnership policies have specific______ requirements under the Deficit Reduction Act of 2005:",
		'answer_a': 'Discrimination',
		'answer_b': 'Age',
		'answer_c': 'Inflation Protection',
		'answer_d': 'Height',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		48: {'question': "Under Medicare,what must have occurred for the same or related condition in order to receive Medicare’s skilled care benefits?",
		'answer_a': 'Medical Condition',
		'answer_b': 'Referral',
		'answer_c': 'Depletion of Benefits',
		'answer_d': 'Hospitalization',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		49: {'question': "In Florida, The Agency for Health Care Administration, in consultation with the Office of Insurance Regulation and the____  is directed to establish a qualified state Long-Term Care Insurance Partnership Program.",
		'answer_a': 'Department of Children and Families',
		'answer_b': 'Department of Insurance',
		'answer_c': 'Division of Investigative & Forensic Services',
		'answer_d': 'Division of Funeral, Cemetery, and Consumer Services',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		50: {'question': "LTC Medicaid recipients are limited to no more than how much in assets?",
		'answer_a': '$30,000',
		'answer_b': '$10,000',
		'answer_c': '$3,000',
		'answer_d': '$50,000',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		51: {'question': "Which is not an unfair claim practices defined under the NAIC?",
		'answer_a': 'Failing to adopt and implement reasonable standards for the prompt investigation and settlement of claims',
		'answer_b': 'Representing to claimants or insureds relevant facts or policy provisions that relate to the coverages at issue',
		'answer_c': 'Not attempting in good faith to settle claims promptly, fairly, and equitably when it is reasonably clear the insurer is liable to pay such claims',
		'answer_d': 'Failing to provide forms necessary to present claims within 15 calendar days of a request for such forms',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		52: {'question': "Which is a non-countable asset to Medicaid?",
		'answer_a': 'Burial plot',
		'answer_b': 'IRAs and other retirement investments',
		'answer_c': 'Nonresident property',
		'answer_d': 'Certificates of deposit and money market accounts',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		53: {'question': "It is often possible to obtain both nursing home benefits and home care benefits in the same policy. In such a case, home care is typically covered at what percentage of the nursing home rate?",
		'answer_a': '100 percent',
		'answer_b': '75 percent',
		'answer_c': '50 percent',
		'answer_d': '25 percent',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		54: {'question': "_____ is when all of used benefits renew after a specific length of time and under specific circumstances.  During this period of time, the policyholder must be claim free.",
		'answer_a': 'Business Output Policy',
		'answer_b': 'Restoration of Policy Benefits',
		'answer_c': 'Motor Truck Policy',
		'answer_d': 'Non Standard Policy',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		55: {'question': "Citizens who elect to enroll in Original Medicare may augment their coverage with:",
		'answer_a': 'Old Age Supplement Insurance',
		'answer_b': 'Disability Supplement Insurance',
		'answer_c': 'Medicaid Supplement Insurance',
		'answer_d': 'Medicare Supplement Insurance',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		56: {'question': " What is the average age of the long-term care insurance policyholder at the time of purchase?",
		'answer_a': '63',
		'answer_b': '83',
		'answer_c': '30',
		'answer_d': '47',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		57: {'question': "Part D of Medicare covers what?",
		'answer_a': 'Hospital Insurance',
		'answer_b': 'Prescription Drugs',
		'answer_c': 'Medical Insurance',
		'answer_d': 'Long-Term-Care Insurance',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		58: {'question': "What is the daily benefit called that will be paid by the insurer if confinement in a nursing home occurs?",
		'answer_a': 'Inclusion amount',
		'answer_b': 'Daily benefit amount',
		'answer_c': 'Dollar-for-Dollar',
		'answer_d': 'Personal property amount',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		59: {'question': "The foundation for the Medicaid program, created by Roosevelt in 1935, was called?",
		'answer_a': 'Medical Assistance (MA)',
		'answer_b': 'Old Age Assistance (OAA)',
		'answer_c': 'Social Assistance (SA)',
		'answer_d': 'Long Term Assistance (LTA)',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},
		60: {'question': "There are two main kinds of Advance Directives: the Living Will and what else?",
		'answer_a': 'Durable Power of Attorney for Health Care',
		'answer_b': 'Non-Living Will',
		'answer_c': 'Health Directive',
		'answer_d': 'Administrative Will',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},


				},

	}

long_term_care_10_final_results = {
	"title": "Florida Discount Continuing Education: Long-Term-Care Final Results",
	"url_pass": "health_course_2_course_complete",
	"url_fail": 'health_course_2_final_prep',
	"answers": {
		1: '12 million',
		2: 'Alzheimer’s Disease',
		3: 'Elimination period',
		4: 'Shopping',
		5: '6 months',
		6: 'Caregiver',
		7: '58 or 59 years old',
		8: '12 weeks',
		9: 'Age',
		10: 'All of the above',
		11: 'Advanced Directive',
		12: 'Height',
		13: 'Home',
		14: 'Aging baby boomers',
		15: 'Custodial Care',
		16: 'Transferring',
		17: '1965',
		18: 'Medicaid',
		19: '20 days',
		20: 'Nursing home',
		21: 'Checking and Savings accounts',
		22: 'Linked benefit policies',
		23: 'Food stamps',
		24: 'Formal care',
		25: 'Minimum Monthly Maintenance Needs Allowance (MMMNA)',
		26: 'All of the above',
		27: 'Benefit amount',
		28: 'Valet services',
		29: '31',
		30: 'Individuals with above-average wealth',
		31: 'Medicaid',
		32: 'The Robert Wood Johnson Foundation',
		33: '40 percent',
		34: 'All of the above',
		35: 'The policy holder must have assets over $100,000',
		36: 'Total asset protection',
		37: '60 months',
		38: 'Driving',
		39: 'Lower the deductible',
		40: 'All of the above',
		41: 'Misrepresentation',
		42: 'Maximum Lifetime Benefit',
		43: 'Acute',
		44: 'Less than 1 percent',
		45: 'Assisting in raising deductibles along with inflation',
		46: 'Hybrid model',
		47: 'Inflation protection',
		48: 'Hospitalization',
		49: 'Department of Children and Families',
		50: '$3,000',
		51: 'Representing to claimants or insureds relevant facts or policy provisions that relate to the coverages at issue',
		52: 'Burial plot',
		53: '50 percent',
		54: 'Restoration of Policy Benefits',
		55: 'Medicare Supplement Insurance',
		56: '63',
		57: 'Prescription Drugs',
		58: 'Daily benefit amoun',
		59: 'Old Age Assistance (OAA)',
		60: 'Durable Power of Attorney for Health Care',

			},

				}

medicare_9_intro = {
	# "session['course']": "life-health-course-4",
	"title": "Medicare & Medicaid: Introduction",
	"course": "Florida 9-Hour Medicare & Medicaid",
	"course_number": "113838",
	"hours_approved": "9  Health Agent Electives (2-40)",
	"price": "$17.10",

	"tagline": "This course fulfills the state-mandated requirements for the Health Agent Electives continuing education component for Florida-licensed agents.(2-40)",
	"summary": "Florida 9-Hour Medicare & Medicaid CE Update For Health Agents examines Medicare, Medicaid, and Insurance Claims for Health Agents \
	in Florida. The course covers the history of Medicare and Medicaid, and the four parts (A,B,C,D). Also discussed is eligibility criteria for each of these programs, as\
	 well as Medicare supplement (Medigap) policies. The course also provides agents with a broad overview to Insurance Claims, fundamentals of the Claims Process, the key\
	  legal concepts and terminology related to Claims, and a familiarity with the roles and responsibilities of the parties involved in Claims.",

	"highlight": {
		1: 'History and purpose of Medicare, Medicaid, and Medicare supplement insurance',
		2: 'Eligibility criteria for each of these programs',
		3: 'The four parts of Medicare',
		4: 'Purpose and features of Medicare supplement (Medigap) policies',
		5: 'Overview of Company Operations and Insurance Fundamentals',
		6: 'Legal Concepts Related to Claims',
		7: 'Claims Investigation Techniques and Tools',
		8: 'Innovations and Advancements in Claims Handling Practices',
		}
	}

medicare_9_chapter_1 = {
	"title": "Medicare & Medicaid: Chapter 1",
	"course": "9-Hour Medicare & Medicaid",
	"chapter_no": 1,
	"chapter_total":  10,
	"pdf": "/static/fl-life-health/course-3-image/chapter-1.pdf",
	"url_results": "health_course_3_chapter_1_results",
	"question_1":"The Medicare Act was created in what year?",
	"answer_1a": "1973",
	"answer_1b": "1965",
	"answer_1c": "1998",
	"answer_1d": "1935",
	"value_1a": "",
	"value_1b": "correct",
	"value_1c": "",
	"value_1d": "",
	"question_2":"How many parts of Medicare are their?",
	"answer_2a": "One",
	"answer_2b": "Two",
	"answer_2c": "Three",
	"answer_2d": "Four",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "correct",
	"result_title": "Medicare & Medicaid: Chapter 1 Results",
	"answer_1": "1965",
	"answer_2": "Four",
	"url_wrong": "health_course_3_chapter_1",
	"url_correct": "health_course_3_chapter_2",
	}

medicare_9_chapter_2 = {
	"title": "Medicare & Medicaid: Chapter 2",
	"course": "9-Hour Medicare & Medicaid",
	"chapter_no": 2,
	"chapter_total":  10,
	"pdf": "/static/fl-life-health/course-3-image/chapter-2.pdf",
	"url_results": "health_course_3_chapter_2_results",
	"question_1":"Medicare was originally targeted to people over what age?",
	"answer_1a": "45",
	"answer_1b": "90",
	"answer_1c": "65",
	"answer_1d": "75",
	"value_1a": "",
	"value_1b": "",
	"value_1c": "correct",
	"value_1d": "",
	"question_2":"Medicare was originally targeted to people over what age?",
	"answer_2a": "Lower",
	"answer_2b": "Higher",
	"answer_2c": "The same",
	"answer_2d": "Zero",
	"value_2a": "",
	"value_2b": "correct",
	"value_2c": "",
	"value_2d": "",
	"result_title": "Medicare & Medicaid: Chapter 2 Results",
	"answer_1": "65",
	"answer_2": "Higher",
	"url_wrong": "health_course_3_chapter_2",
	"url_correct": "health_course_3_chapter_3",
	}

medicare_9_chapter_3 = {
	"title": "Medicare & Medicaid: Chapter 3",
	"course": "9-Hour Medicare & Medicaid",
	"chapter_no": 3,
	"chapter_total":  10,
	"pdf": "/static/fl-life-health/course-3-image/chapter-3.pdf",
	"url_results": "health_course_3_chapter_3_results",
	"question_1":"How many days of coverage in a skilled nursing facility will the Original Medicare pay for in full?",
	"answer_1a": "100 days",
	"answer_1b": "7 days",
	"answer_1c": "50 days",
	"answer_1d": "20 days",
	"value_1a": "",
	"value_1b": "",
	"value_1c": "",
	"value_1d": "correct",
	"question_2":"Which is an example of a service that would fall under Medicare Part B?",
	"answer_2a": "Hospice care",
	"answer_2b": "Home health care",
	"answer_2c": "Occupational therapy ",
	"answer_2d": "Inpatient care in a skilled nursing facility",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "correct",
	"value_2d": "",
	"result_title": "Medicare & Medicaid: Chapter 3 Results",
	"answer_1": "20 days",
	"answer_2": "Occupational therapy",
	"url_wrong": "health_course_3_chapter_3",
	"url_correct": "health_course_3_chapter_4",
	}

medicare_9_chapter_4 = {
	"title": "Medicare & Medicaid: Chapter 4",
	"course": "9-Hour Medicare & Medicaid",
	"chapter_no": 4,
	"chapter_total":  10,
	"pdf": "/static/fl-life-health/course-3-image/chapter-4.pdf",
	"url_results": "health_course_3_chapter_4_results",
	"question_1":"Medicare Advantage is often called which plan?",
	"answer_1a": "Medicare Part A",
	"answer_1b": "Medicare Part B",
	"answer_1c": "Medicare Part C",
	"answer_1d": "Medicare Part D",
	"value_1a": "",
	"value_1b": "",
	"value_1c": "correct",
	"value_1d": "",
	"question_2":"Medicare Advantage plans, except for private contracts, must provide coverage for all services currently available under which Medicare parts? ",
	"answer_2a": "Medicare Parts A and C",
	"answer_2b": "Medicare Parts A and B",
	"answer_2c": "Medicare Parts B and D",
	"answer_2d": "Medicare Parts C and D",
	"value_2a": "",
	"value_2b": "correct",
	"value_2c": "",
	"value_2d": "",
	"result_title": "Medicare & Medicaid: Chapter 4 Results",
	"answer_1": "Medicare Part C",
	"answer_2": "Medicare Part A and B",
	"url_wrong": "health_course_3_chapter_4",
	"url_correct": "health_course_3_chapter_5",
	}

medicare_9_chapter_5 = {
	"title": "Medicare & Medicaid: Chapter 5",
	"course": "9-Hour Medicare & Medicaid",
	"chapter_no": 5,
	"chapter_total":  10,
	"pdf": "/static/fl-life-health/course-3-image/chapter-5.pdf",
	"url_results": "health_course_3_chapter_5_results",
	"question_1":"Medicare Supplement Plans are synonymous with what term?",
	"answer_1a": "Medicaid",
	"answer_1b": "Shelfgap",
	"answer_1c": "Suppligap",
	"answer_1d": "Medigap",
	"value_1a": "",
	"value_1b": "",
	"value_1c": "",
	"value_1d": "correct",
	"question_2":"Basic Supplement plans do what?",
	"answer_2a": "Add on long term care",
	"answer_2b": "Cover most hospital costs",
	"answer_2c": "Fill the gaps in Original Medicare Coverage",
	"answer_2d": "None of the above",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "correct",
	"value_2d": "",
	"result_title": "Medicare & Medicaid: Chapter 5 Results",
	"answer_1": "Medigap",
	"answer_2": "Fill the gaps in Original Medicare Coverage",
	"url_wrong": "health_course_3_chapter_5",
	"url_correct": "health_course_3_chapter_6",
	}

medicare_9_chapter_6 = {
	"title": "Medicare & Medicaid: Chapter 6",
	"course": "9-Hour Medicare & Medicaid",
	"chapter_no": 6,
	"chapter_total":  10,
	"pdf": "/static/fl-life-health/course-3-image/chapter-6.pdf",
	"url_results": "health_course_3_chapter_6_results",
	"question_1":"Medicaid is a federally aided, state-operated program of health care assistance for who?",
	"answer_1a": "The poor",
	"answer_1b": "The elderly",
	"answer_1c": "The rich",
	"answer_1d": "All of the above",
	"value_1a": "correct",
	"value_1b": "",
	"value_1c": "",
	"value_1d": "",
	"question_2":"Which is not a requirement for Medicaid eligibility?",
	"answer_2a": "Proof of disability or age",
	"answer_2b": "Receiving Medicare",
	"answer_2c": "Income limitations",
	"answer_2d": "Asset limitations",
	"value_2a": "",
	"value_2b": "correct",
	"value_2c": "",
	"value_2d": "",
	"result_title": "Medicare & Medicaid: Chapter 6 Results",
	"answer_1": "The poor",
	"answer_2": "Receiving Medicare",
	"url_wrong": "health_course_3_chapter_6",
	"url_correct": "health_course_3_chapter_7",
	}

medicare_9_chapter_7 = {
	"title": "Medicare & Medicaid: Chapter 7",
	"course": "9-Hour Medicare & Medicaid",
	"chapter_no": 7,
	"chapter_total":  10,
	"pdf": "/static/fl-life-health/course-3-image/chapter-7.pdf",
	"url_results": "health_course_3_chapter_7_results",
	"question_1":"Any conscious action (or decision not to act) that identifies and reduces the frequency, severity, or unpredictability of loss claims?",
	"answer_1a": "Insuring Claimant’s Rights",
	"answer_1b": "Risk Management",
	"answer_1c": "Appraising Damages",
	"answer_1d": "Adjusting Claims",
	"value_1a": "",
	"value_1b": "correct",
	"value_1c": "",
	"value_1d": "",
	"question_2":"When identifying possible risk exposures, risk management professional must be able to do which of the following?",
	"answer_2a": "Test the significance of these actual loss exposures by the degree to which they may occur and disclose to clients the possible results and remedies",
	"answer_2b": "Employ proper methods for identifying those specific loss exposures that particular persons or organization faces at a particular time",
	"answer_2c": "Apply a logical classification scheme for identifying all possible exposures to loss",
	"answer_2d": "All of the above",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "correct",
	"result_title": "Medicare & Medicaid: Chapter 7 Results",
	"answer_1": "Risk Management",
	"answer_2": "All of the above",
	"url_wrong": "health_course_3_chapter_7",
	"url_correct": "health_course_3_chapter_8",
	}

medicare_9_chapter_8 = {
	"title": "Medicare & Medicaid: Chapter 8",
	"course": "9-Hour Medicare & Medicaid",
	"chapter_no": 8,
	"chapter_total":  10,
	"pdf": "/static/fl-life-health/course-3-image/chapter-8.pdf",
	"url_results": "health_course_3_chapter_8_results",
	"question_1":"What are the two types of insurance companies?",
	"answer_1a": "Mutual insurance company & Stock insurance company",
	"answer_1b": "Public insurance company & Private insurance company",
	"answer_1c": "Mutual insurance company & Medical insurance company",
	"answer_1d": "Public insurance company & Stock insurance company",
	"value_1a": "correct",
	"value_1b": "",
	"value_1c": "",
	"value_1d": "",
	"question_2":"Which department within a Claims Division of a large insurance carrier supervises adjusters?",
	"answer_2a": "Corporate claims office",
	"answer_2b": "Branch claims office",
	"answer_2c": "Regional claims office",
	"answer_2d": "National claims office",
	"value_2a": "",
	"value_2b": "correct",
	"value_2c": "",
	"value_2d": "",
	"result_title": "Medicare & Medicaid: Chapter 8 Results",
	"answer_1": "Mutual insurance company & Stock insurance company",
	"answer_2": "Branch claims office",
	"url_wrong": "health_course_3_chapter_8",
	"url_correct": "health_course_3_chapter_9",
	}

medicare_9_chapter_9 = {
	"title": "Medicare & Medicaid: Chapter 9",
	"course": "9-Hour Medicare & Medicaid",
	"chapter_no": 9,
	"chapter_total":  10,
	"pdf": "/static/fl-life-health/course-3-image/chapter-9.pdf",
	"url_results": "health_course_3_chapter_9_results",
	"question_1":"What should every good investigator strive to uncover?",
	"answer_1a": "Opinions and pictures",
	"answer_1b": "Evidence and valid facts",
	"answer_1c": "Monies owed to claimant's",
	"answer_1d": "All of the above",
	"value_1a": "",
	"value_1b": "correct",
	"value_1c": "",
	"value_1d": "",
	"question_2":"Property upon which the total value has been paid as a result of a claim under an insurance policy is known as what?",
	"answer_2a": "Garbage",
	"answer_2b": "Salvage",
	"answer_2c": "Appraisal Property",
	"answer_2d": "Junk market material",
	"value_2a": "",
	"value_2b": "correct",
	"value_2c": "",
	"value_2d": "",
	"result_title": "Medicare & Medicaid: Chapter 9 Results",
	"answer_1": "Evidence and valid facts",
	"answer_2": "Salvage",
	"url_wrong": "health_course_3_chapter_9",
	"url_correct": "health_course_3_chapter_10",
	}

medicare_9_chapter_10 = {
	"title": "Medicare & Medicaid: Chapter 10",
	"course": "9-Hour Medicare & Medicaid",
	"chapter_no": 10,
	"chapter_total":  10,
	"pdf": "/static/fl-life-health/course-3-image/chapter-10.pdf",
	"url_results": "health_course_3_chapter_10_results",
	"question_1":"Which is not a good habit for responsible claims management?",
	"answer_1a": "Keep the insured client advised",
	"answer_1b": "Explore the possibility of settlement",
	"answer_1c": "Focusing on your fees",
	"answer_1d": "Consider the insured’s interest",
	"value_1a": "",
	"value_1b": "",
	"value_1c": "correct",
	"value_1d": "",
	"question_2":"How does technology make managing claims better?",
	"answer_2a": "Electronic and web claims processing",
	"answer_2b": "Improvement in insurer “legacy” computers",
	"answer_2c": "Cost reduction through automation",
	"answer_2d": "All of the above",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "correct",
	"result_title": "Medicare & Medicaid: Chapter 10 Results",
	"answer_1": "Focusing on your fees",
	"answer_2": "All of the above",
	"url_wrong": "health_course_3_chapter_10",
	"url_correct": "security_question",
	'url':'health_course_3_final_prep',
	'last_chapter':True,

}


medicare_9_final_prep = {
	"title": "Florida Discount Continuing Education: Medicare & Medicaid Final Prep",
	"course": "9-Hour Medicare & Medicaid",
	"url_final_exam":"health_course_3_final_exam",
	"url_review":"health_course_3_review",
	}

medicare_9_review = {
	"title": "Florida Discount Continuing Education: Medicare & Medicaid Review",
	"url_final_prep": "health_course_3_final_prep",
	"pdf": "/static/fl-life-health/course-3-image/full-course.pdf",
	}

medicare_9_final_exam = {
	"title": "Florida Discount Continuing Education: Medicare & Medicaid Final",
	"course": "9-Hour Medicare/Medicaid & Insurance Claims",
	"url_final_results": "health_course_3_final_results",

	"questions": {
		1: {'question': "As a general rule, a person needs to have accumulated how many quarters of qualified credits to be entitled to Medicare coverage?",
		'answer_a': '10 quarters ',
		'answer_b': '20 quarters ',
		'answer_c': '30 quarters ',
		'answer_d': '40 quarters ',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': '',
		'value_d': 'correct',
			},
		2: {'question': "Medicare Advantage was created in what government Act?",
		'answer_a': 'Medicare Act of 1965',
		'answer_b': 'Medicare Prescription Drug Improvement and Modernization Act of 2003',
		'answer_c': 'Balanced Budget Act of 1997',
		'answer_d': 'Medicare Improvements for Patients and Providers Act (MIPPA 2008)',
		'value_a': 'w',
		'value_b': 't',
		'value_c': 'correct',
		'value_d': 'w',
			},
		3: {'question': "Under this type of coverage, a carrier will pay replacement cost instead of actual cash value for lost or damaged property?",
		'answer_a': 'Property value',
		'answer_b': 'Actual cash value',
		'answer_c': 'Replacement cost coverage ',
		'answer_d': 'Damage control coverage',
		'value_a': 'w',
		'value_b': '',
		'value_c': 'correct',
		'value_d': 'w',
			},

		4: {'question': "Which Act created the first large-scale reorganization of health care coverage and delivery in the United States?",
		'answer_a': 'Patient Protection and Affordability Care Act',
		'answer_b': 'Social Security Act of 1998',
		'answer_c': 'The False Claims Act',
		'answer_d': 'Family and Medical Leave Act',
		'value_a': 'correct',
		'value_b': '',
		'value_c': 'w',
		'value_d': 'w',
			},

		5: {'question': "Medicare Advantage was originally called?",
		'answer_a': 'Medicare + Medicaid program',
		'answer_b': 'Medicare + Advantage program',
		'answer_c': 'Medicare + Choice program ',
		'answer_d': 'Advantage + Choice program',
		'value_a': 'w',
		'value_b': '',
		'value_c': 'correct',
		'value_d': 'w',
			},

		6: {'question': "What would happen if an insured had intentionally concealed or misrepresented any material fact or circumstance?",
		'answer_a': 'The part of the policy misrepresented will be void',
		'answer_b': 'The entire policy will be void',
		'answer_c': 'Deductibles will increase',
		'answer_d': 'They will pay a penalty',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		7: {'question': "During an approved hospital admission, which part of Medicare will help pay for a semi-private room?",
		'answer_a': 'Medicare Part A',
		'answer_b': 'Medicare Part B',
		'answer_c': 'Medicare Part C',
		'answer_d': 'Medicare Part D',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		8: {'question': "Coverage in a skilled nursing facility is limited to a maximum of how many days per benefit period?",
		'answer_a': '10 days',
		'answer_b': '21 days',
		'answer_c': '52 days',
		'answer_d': '100 days',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		9: {'question': "A Medicare Advantage HMO plan is composed of what?",
		'answer_a': 'Its own network of doctors and hospitals ',
		'answer_b': 'Outside network of doctors and hospitals ',
		'answer_c': 'Private fee-for-service doctors and hospitals',
		'answer_d': 'Any of the above',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		10: {'question': "In regards to Medicaid, which of the following would a state not be allowed to do?",
		'answer_a': 'Reduce eligibility in order to balance the budget',
		'answer_b': 'Establish provisions for reimbursement to providers',
		'answer_c': 'Expand health care services above the minimum',
		'answer_d': 'Expand eligibility to groups above the minimum required by the federal government ',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		11: {'question': "What does notification of a loss to an insurance company by a policyholder or a third person constitute?",
		'answer_a': 'An adjustment',
		'answer_b': 'A payout',
		'answer_c': 'A claim',
		'answer_d': 'An appraisal',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		12: {'question': "What type of program is Medicare referred to as?",
		'answer_a': 'Welfare program',
		'answer_b': 'Entitlement program',
		'answer_c': 'Title program',
		'answer_d': 'Services program',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		13: {'question': "What policies extend coverage for liability for activities that occur over a policy year, notwithstanding the fact that a suit might be brought at a later date to determine liability on the part of a carrier?",
		'answer_a': 'Private coverage',
		'answer_b': 'Appraisal coverage',
		'answer_c': 'Risk coverage',
		'answer_d': 'Occurrence coverage ',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		14: {'question': "What is the purpose of Basic Medicare Supplemental Insurance?",
		'answer_a': 'Fills the “gaps” in Original Medicare coverage ',
		'answer_b': 'Adds long term care coverage',
		'answer_c': 'Adds more “gaps” in Original Medicare coverage',
		'answer_d': 'Replaces the Original Medicare plan',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		15: {'question': "Medigap Plan C includes all of the Plan A basic benefits, plus:",
		'answer_a': 'Coverage for the Medicare Part A inpatient hospital deductible',
		'answer_b': 'Coverage for the skilled nursing facility care coinsurance amount',
		'answer_c': 'Coverage for the Medicare Part B deductible',
		'answer_d': 'All of the above ',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		16: {'question': "The person who is protected against loss and may or may not be the owner of the insurance policy is?",
		'answer_a': 'The owner',
		'answer_b': 'The insured',
		'answer_c': 'The appraiser',
		'answer_d': 'The underwiter',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		17: {'question': "Which part of Medicare would pay for inpatient care in a general or psychiatric hospital?",
		'answer_a': 'Part A',
		'answer_b': 'Part B',
		'answer_c': 'Part C',
		'answer_d': 'Part D',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		18: {'question': "Medicare Medical Savings Account plans (MSA's ) combine which two components?",
		'answer_a': "PPO's and HMO's",
		'answer_b': 'High-deductible MA policies with a medical savings account',
		'answer_c': 'Network and Non-network doctors and hospitals',
		'answer_d': 'Low-deductible MA policies with Social Security',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		19: {'question': "New standards introduced in September 1996 require property owners who are selling or renting real estate built prior to____ to disclose any known lead-based paint or lead hazards.",
		'answer_a': '1988',
		'answer_b': '1977',
		'answer_c': '1999',
		'answer_d': '2001',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		20: {'question': "The company that extends insurance coverage over the subject matter by the sale of a contract known as an insurance policy is called what?",
		'answer_a': 'Assister',
		'answer_b': 'Issuer',
		'answer_c': 'Underwriter',
		'answer_d': 'Writer',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		21: {'question': "There are basically two types of Medicare Advantage plans, what are they?",
		'answer_a': 'Deductible and Non-deductible',
		'answer_b': 'Network and Non-network',
		'answer_c': 'Countable and Non-countable',
		'answer_d': 'Medicare and Medicaid',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		22: {'question': "What do you call the first peril in a chain of events without which a loss would not have been sustained?",
		'answer_a': 'Benefit cause',
		'answer_b': 'Secondary cause',
		'answer_c': 'Shared cause',
		'answer_d': 'Proximate cause',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'corrrect',
			},

		23: {'question': "In an insurance policy, the relative obligations and responsibilities of both the carrier and the policyholder is called what?",
		'answer_a': 'The Declaration Page',
		'answer_b': 'The Insurance Agreement',
		'answer_c': 'The Deductible',
		'answer_d': 'Cancellation',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		24: {'question': "This occurs when there is damage to the property or health of a person other than the insured:",
		'answer_a': 'A “first-party loss”',
		'answer_b': 'A “second-party loss”',
		'answer_c': 'A “third-party loss”',
		'answer_d': 'A “fourth-party loss”',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		25: {'question': "Medicare supplement policies are what type insurance plans?",
		'answer_a': 'Assisted insurance plans',
		'answer_b': 'Government insurance plans',
		'answer_c': 'Public insurance plans',
		'answer_d': 'Private insurance plans ',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		26: {'question': "Which policiy provide insurance coverage against liability for any claims that are presented to an insurance carrier during a policy year, regardless of when the underlying conduct giving rise to the liability occurred?",
		'answer_a': 'Non-Occurence policy',
		'answer_b': 'Plan A policy',
		'answer_c': 'Occurence policy',
		'answer_d': 'Claims-made policy',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		27: {'question': "Which is not one of the habits for responsible claims management?",
		'answer_a': 'Keep the insured client advised',
		'answer_b': 'Listen to the advice of defense counsel',
		'answer_c': 'Do not deplete the policy carelessly when there are multiple claims',
		'answer_d': 'Do not explore the possibility of settlement',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		28: {'question': "Which is one of the four corporate divisions of most insurance companies?",
		'answer_a': 'Underwriting',
		'answer_b': 'Finance',
		'answer_c': 'Claims',
		'answer_d': 'All of the above',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		29: {'question': "If certain conditions are met, Medicare will fully cover the first how many days of care in a skilled nursing facility (SNF) during each benefit period?",
		'answer_a': '1 month',
		'answer_b': '1 week',
		'answer_c': '20 days',
		'answer_d': '90 days',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		30: {'question': "What are periodic payments made during the term of an insurance policy by an owner to the issuer for insuring against a loss called?",
		'answer_a': 'Deductibles',
		'answer_b': 'Premiums',
		'answer_c': 'Appraials',
		'answer_d': 'Interest',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		31: {'question': "What is the provision called that each carrier will pay a fair proportion of a loss when there is more than one policy in effect for the same property?",
		'answer_a': 'Pro Rata Contributions ',
		'answer_b': 'Cancellation',
		'answer_c': 'The Insurance Agreement',
		'answer_d': 'Property & Casualty',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		32: {'question': "Which system pays a hospital a preset amount for a certain number of days of care for each diagnosis rather than each hospital submitting bills for a patient’s stay?",
		'answer_a': 'Prospective Payment System (PPS) ',
		'answer_b': 'Depletion of Benefits System',
		'answer_c': 'Referral System',
		'answer_d': 'Medical Condition System',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		33: {'question': "Who is the ultimate interpreter of an insurance policy?",
		'answer_a': 'Courts',
		'answer_b': 'Policyholder',
		'answer_c': 'Attorney',
		'answer_d': 'Carrier',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		34: {'question': "Which party could be involved in an insurance claim?",
		'answer_a': 'Mediator',
		'answer_b': 'Arbitrator',
		'answer_c': 'Lawyer',
		'answer_d': 'All of the above',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		35: {'question': "What is not an element of a valid claim?",
		'answer_a': 'Losse must be fortuitous',
		'answer_b': 'A loss must be sustained',
		'answer_c': 'Losses can be intentionally caused by the policyholder',
		'answer_d': 'Losses must be occasioned by an extraneous factor',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		36: {'question': "Generally, the burden of proving the existence of a loss is upon whom?",
		'answer_a': 'Policyholder',
		'answer_b': 'Insurer',
		'answer_c': 'Mediator',
		'answer_d': 'Injured',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		37: {'question': "Which part of Medicare will pay for hospice care?",
		'answer_a': 'Medicare Part A',
		'answer_b': 'Medicare Part B',
		'answer_c': 'Medicare Part C',
		'answer_d': 'Medicare Part D',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		38: {'question': "Which is a mandated service covered by Medicare?",
		'answer_a': 'Inpatient and outpatient acute care services ',
		'answer_b': 'Long-term care for the elderly and mentally ill',
		'answer_c': 'Medicare Part B premiums for elderly persons in poverty',
		'answer_d': 'All of the above',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		39: {'question': "In a claim involving death due to an accident, what  statute may apply where a surviving spouse, parents or children of the deceased may recover damages from the party responsible for the death?",
		'answer_a': 'Accidental deceased statute',
		'answer_b': 'Survivor\'s law',
		'answer_c': 'Wrongful death statute',
		'answer_d': 'Next of kin statute',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		40: {'question': "If language in an insurance  policy is capable of being interpreted in two different ways, who will the courts favor?",
		'answer_a': 'Attorneys',
		'answer_b': 'Insurers',
		'answer_c': 'Adjusters',
		'answer_d': 'Policyholders ',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		41: {'question': "What is something Medicare Part A will not pay for?",
		'answer_a': 'Lab tests',
		'answer_b': 'Telephone',
		'answer_c': 'Semi-private room',
		'answer_d': 'Rehabilitation services, such as physical therapy',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		42: {'question': "Which is not one of the unfair claims practices in the Model Unfair Claim Settlement Practices Act?",
		'answer_a': 'Failing to adopt and maintain sound criteria for the investigation and processing of claims',
		'answer_b': 'Acting promptly upon notification of a claim arising under a policy',
		'answer_c': 'Misstating policy terms or relevant facts that affect coverage',
		'answer_d': 'Misrepresenting the statute of limitations',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		43: {'question': "Insurers claim to be losing how much a year to fraud?",
		'answer_a': '$15 - $20 billion',
		'answer_b': '$85 - $120 billion',
		'answer_c': '$85 - $120 million',
		'answer_d': '$15 - $20 million',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		44: {'question': "Many claim experts feel that the first_____ following a loss  is the time when losses can be minimized and excess claims and client dissatisfaction avoided. ",
		'answer_a': '48 hours',
		'answer_b': '1 week',
		'answer_c': '2 weeks',
		'answer_d': '1 month',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		45: {'question': "What is the only type of nursing facility Medicare will pay for?",
		'answer_a': 'Custodial nursing facility',
		'answer_b': 'Coverage nursing facility',
		'answer_c': 'Skilled nursing facility',
		'answer_d': 'Assured nursing facility',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		46: {'question': "What constitutes an equitable insurance practice under the Insurance Consumer’s Bill of Rights and Responsibilities?",
		'answer_a': 'The right to a voice',
		'answer_b': 'The right to safeguards',
		'answer_c': 'The right to a remedy',
		'answer_d': 'All of the above',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		47: {'question': "The Patient Protection and Affordability Act expanded Medicaid for whom?",
		'answer_a': 'Groups under age 65 with incomes up to 138 percent of the federal poverty level',
		'answer_b': 'Individuals over 65 with incomes less than 138 percent of the federal poverty level',
		'answer_c': 'Individuals under age 65 with incomes up to 238 percent of the federal poverty level',
		'answer_d': 'Individuals under age 65 with incomes up to 138 percent of the federal poverty level',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		48: {'question': "A professional, trained in the examination, evaluation, and dispensation of claims is called:",
		'answer_a': 'An Appealer',
		'answer_b': 'An Underwriter',
		'answer_c': 'An Appraiser',
		'answer_d': 'An Adjuster',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		49: {'question': "Under Medicare,what must have occurred in order to receive Medicare’s skilled nursing care benefits?",
		'answer_a': 'Hospitalization for at least 3 consecutive days ',
		'answer_b': 'Depletion of benefits',
		'answer_c': 'Wrongful death',
		'answer_d': 'Medical condition',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		50: {'question': "The rights of a carrier to legally recoup the amount of settlement from a third party who is responsible for a loss after payment of a claim is called:",
		'answer_a': 'Cancellation',
		'answer_b': 'Obligation',
		'answer_c': 'Subrogation',
		'answer_d': 'Adjustement',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

				},

	}

medicare_9_final_results = {
	"title": "Florida Discount Continuing Education: Long-Term-Care Final Results",
	"url_pass": "health_course_3_course_complete",
	"url_fail": 'health_course_3_final_prep',
	"answers": {
		1: '40 quarters',
		2: 'Balanced Budget Act of 1997',
		3: 'Replacement cost coverage',
		4: 'Patient Protection and Affordability Care Act',
		5: 'Medicare + Choice program',
		6: 'The entire policy will be void ',
		7: 'Medicare Part A ',
		8: '100 days',
		9: 'Its own network of doctors and hospitals',
		10: 'Reduce eligibility in order to balance the budget ',
		11: 'A Claim',
		12: 'Entitlement program',
		13: 'Occurrence coverage',
		14: 'Fills the “gaps” in Original Medicare coverage',
		15: 'All of the above',
		16: 'The insured',
		17: 'Part A',
		18: 'High-deductible MA policies with a medical savings account ',
		19: '1977',
		20: 'Issuer',
		21: 'Network and Non-network',
		22: 'Proximate cause',
		23: 'The Insurance Agreement',
		24: 'A “third-party loss”',
		25: 'Private insurance plans',
		26: 'Claims-made policy',
		27: 'Do not explore the possibility of settlement',
		28: 'All of the above',
		29: '20 days',
		30: 'Premiums',
		31: 'Pro Rata Contributions',
		32: 'Prospective Payment System (PPS)',
		33: 'Courts',
		34: 'All of the above',
		35: 'Losses can be intentionally caused by the policyholder',
		36: 'Policyholder',
		37: 'Medicare Part A ',
		38: 'All of the above',
		39: 'Wrongful death statute',
		40: 'Policyholders',
		41: 'Telephone',
		42: 'Acting promptly upon notification of a claim arising under a policy ',
		43: '$85 - $120 billion',
		44: '48 hours',
		45: 'Skilled nursing facility',
		46: 'All of the above',
		47: 'Individuals under age 65 with incomes up to 138 percent of the federal poverty level ',
		48: 'An Adjuster ',
		49: 'Hospitalization for at least 3 consecutive days',
		50: 'Subrogation',

			},

				}
