
nfip_3_intro = {
	# "session['course']": "life-health-course-4",
	"title": "National Flood Insurance Program: Introduction",
	"course": "3-Hour National Flood Insurance Program",
	"course_number": "113181",
	"hours_approved": "3 All-Lines Adjuster Electives (2-15 & 2-18)",
	"price": "$5.70",

	"tagline": "This course fulfills the state-mandated requirements for the All-Lines Adjuster Electives continuing education component for Florida-licensed agents.(5-20 & 6-20)",
	"summary": "In this course we will review the fundamental concepts and the complex coverage details involving The National Flood Insurance Program.",

	"highlight": {
		1: 'Creation of NFIP',
		2: 'The Role of FEMA',
		3: 'Increased Cost of Compliance Coverage',
		4: 'Damages and Property Not Covered',
		5: 'Claims Handling Procedures',
		6: 'Other Issues Affecting Flood Coverage',
		}
	}

nfip_3_chapter_1 = {
	"title": "National Flood Insurance Program: Chapter 1",
	"course": "3-Hour National Flood Insurance Program",
	"chapter_no": 1,
	"chapter_total":  5,
	"pdf": "/static/pa-course-4-image/chapter-1.pdf",
	"url_results": "ia_course_4_chapter_1_results",
	"question_1":"Which is not one of Standard Flood Insurance Policy forms?",
	"answer_1a": "Residential Condominium Building Association",
	"answer_1b": "Single Family",
	"answer_1c": "Dwelling",
	"answer_1d": "General Property",
	"value_1a": "",
	"value_1b": "correct",
	"value_1c": "",
	"value_1d": "",
	"question_2":"What is the waiting period for a NFIP policy to take effect?",
	"answer_2a": "60 days",
	"answer_2b": "14 days",
	"answer_2c": "30 days",
	"answer_2d": "7 days",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "correct",
	"value_2d": "",
	"result_title": "NFIP: Chapter 1 Results",
	"answer_1": "Single Family",
	"answer_2": "30 days",
	"url_wrong": "ia_course_4_chapter_1",
	"url_correct": "ia_course_4_chapter_2",
	}

nfip_3_chapter_2 = {
	"title": "National Flood Insurance Program: Chapter 2",
	"course": "3-Hour National Flood Insurance Program",
	"chapter_no": 2,
	"chapter_total":  5,
	"pdf": "/static/pa-course-4-image/chapter-2.pdf",
	"url_results": "ia_course_4_chapter_2_results",
	"question_1":"How does a community get into the National Flood Insurance Program?",
	"answer_1a": "It contacts FEMA and requests admission to the NFIP",
	"answer_1b": "It applies after multiple floods",
	"answer_1c": "It happens automatically after an emergency is declared",
	"answer_1d": "All communities are in the NFIP",
	"value_1a": "correct",
	"value_1b": "",
	"value_1c": "",
	"value_1d": "",
	"question_2":"Flood insurance may not be available for buildings and \
	their contents located in these locations:",
	"answer_2a": "Emergency Areas",
	"answer_2b": "Flood Zones",
	"answer_2c": "Coastal Barrier Resources Systems",
	"answer_2d": "National Emergency Training Centers",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "correct",
	"value_2d": "",
	"result_title": "NFIP: Chapter 2 Results",
	"answer_1": "It contacts FEMA and requests admission to the NFIP",
	"answer_2": "Coastal Barrier Resources Systems",
	"url_wrong": "ia_course_4_chapter_2",
	"url_correct": "ia_course_4_chapter_3",
	}

nfip_3_chapter_3 = {
	"title": "National Flood Insurance Program: Chapter 3",
	"course": "3-Hour National Flood Insurance Program",
	"chapter_no": 3,
	"chapter_total":  5,
	"pdf": "/static/pa-course-4-image/chapter-3.pdf",
	"url_results": "ia_course_4_chapter_3_results",
	"question_1":"Which is not a characteristic of the NFIP?",
	"answer_1a": "Likely unable to purchase reinsurance to cover catastrophic losses ",
	"answer_1b": "Structured to build a capital surplus",
	"answer_1c": "Unable to reject high-risk applicants",
	"answer_1d": "Subject to statutory limits on rate increases",
	"value_1a": "",
	"value_1b": "correct",
	"value_1c": "",
	"value_1d": "",
	"question_2":"What does NFIP call properties that have had two or more \
	flood insurance claims payments of $1,000 or more over 10 years?",
	"answer_2a": "Flood Prone Properties",
	"answer_2b": "Non-insurable Properties",
	"answer_2c": "FEMA Special Properties",
	"answer_2d": "Repetitive Loss Properties",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "correct",
	"result_title": "NFIP: Chapter 3 Results",
	"answer_1": "Structured to build a capital surplus",
	"answer_2": "Repetitive Loss Properties",
	"url_wrong": "ia_course_4_chapter_3",
	"url_correct": "ia_course_4_chapter_4",
	}

nfip_3_chapter_4 = {
	"title": "National Flood Insurance Program: Chapter 4",
	"course": "3-Hour National Flood Insurance Program",
	"chapter_no": 4,
	"chapter_total":  5,
	"pdf": "/static/pa-course-4-image/chapter-4.pdf",
	"url_results": "ia_course_4_chapter_4_results",
	"question_1": "The purpose of the Flood Insurance Rate Map is to provide information needed by agents, lending institutions, \
	community officials, flood zone determination companies, and private citizens who need to know:",
	"answer_1a": "The specific location of a building within a SFHA",
	"answer_1b": "The flood zone assigned to a specific building location",
	"answer_1c": "The Base Flood Elevation of a building",
	"answer_1d": "All of the above",
	"value_1a": "",
	"value_1b": "",
	"value_1c": "",
	"value_1d": "correct",
	"question_2":"What is the unit used to signify what a building's lowest floor should be elevated to?",
	"answer_2a": "Base Flood Elevation",
	"answer_2b": "Special Flood Hazard Area",
	"answer_2c": "Flood Hazard Boundary Map",
	"answer_2d": "Unit of Map Amendment",
	"value_2a": "correct",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "",
	"result_title": "NFIP: Chapter 4 Results",
	"answer_1": "All of the above",
	"answer_2": "Base Flood Elevation",
	"url_wrong": "ia_course_4_chapter_4",
	"url_correct": "ia_course_4_chapter_5",
	}

nfip_3_chapter_5 = {
	"title": "National Flood Insurance Program: Chapter 5",
	"course": "3-Hour National Flood Insurance Program",
	"chapter_no": 5,
	"chapter_total":  5,
	"pdf": "/static/pa-course-4-image/chapter-ia-5.pdf",
	"url_results": "ia_course_4_chapter_5_results",
	"question_1": "In 1981, NFIP administrators, after discussions with \
	congress, started setting NFIP's subsidized premium rates based on what calculation?",
	"answer_1a": "Average historical loss",
	"answer_1b": "Corporate adjuster algorithm",
	"answer_1c": "Average historical gains",
	"answer_1d": "National index function",
	"value_1a": "correct",
	"value_1b": "",
	"value_1c": "",
	"value_1d": "",
	"question_2":"Which Act was a United States Congress bill that would have delayed the increases in flood \
	insurance premiums that were part of the Biggert–Waters Flood Insurance Reform Act?",
	"answer_2a": "The Bunning-Bereuter-Blumenauer Flood Insurance Reform Act",
	"answer_2b": "Materials Flood Damage Act",
	"answer_2c": "The National Flood Insurance Act",
	"answer_2d": "The Homeowner Flood Insurance Affordability Act",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "correct",
	"result_title": "NFIP: Chapter 5 Results",
	"answer_1": "Average historical loss",
	"answer_2": "The Homeowner Flood Insurance Affordability Act",
	"url_wrong": "ia_course_4_chapter_5",
	"url_correct": "security_question",
	'url':'ia_course_4_final_prep',
	'last_chapter':True,
	}

nfip_3_final_prep = {
	"title": "Florida Discount Continuing Education: NFIP Final Prep",
	"course": "3-Hour National Flood Insurance Program",
	"url_final_exam":"ia_course_4_final_exam",
	"url_review":"ia_course_4_review",

	}

nfip_3_review = {
	"title": "Florida Discount Continuing Education: NFIP Review",
	"url_final_prep": "ia_course_4_final_prep",
	"pdf": "/static/pa-course-4-image/full-course.pdf",

	}

# unused here is architecturee for final exam.  I decided not to move forward on this one because I already have the quiz written from pa-nfip
nfip_3_final_exam = {
	"title": "Florida Discount Continuing Education: NFIP Final",
	"course": "3-Hour National Flood Insurance Program",
	"url_final_results": "ia_course_4_final_results",
	"pdf": "/static/pa-course-4-image/full-course.pdf",

	"questions": {
		1: {'question': "In designing NFIP, Congress required that premiums for certain properties be offered at prices below those for full-risk premiums. Why?",
		'answer_a': 'A1',
		'answer_b': 'B1',
		'answer_c': 'C1',
		'answer_d': 'D1',
		'value_a': 'correct',
		'value_b': '',
		'value_c': '',
		'value_d': '',
			},
		2: {'question': "2222222 full-risk premiums. /Why?",
		'answer_a': 'A2',
		'answer_b': 'B2',
		'answer_c': 'C2',
		'answer_d': 'D2',
		'value_a': '',
		'value_b': 'correct',
		'value_c': '',
		'value_d': '',
			},
		3: {'question': "In design33333?????",
		'answer_a': 'A3',
		'answer_b': 'B3',
		'answer_c': 'C3',
		'answer_d': 'D3',
		'value_a': '',
		'value_b': 'correct',
		'value_c': '',
		'value_d': '',
			},
				},

	}

#template final exam  not used
insurance_claims_5_final_exam = {
	"title": "Florida Discount Continuing Education: Insurance Claims Final",
	"course": "5-Hour Insurance Claims Update",
	"url_final_results": "life_health_course_4_final_results",


	"questions": {
		1: {'question': "?",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': '',
		'value_d': 'w',
			},
		2: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},
		3: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': '',
		'value_c': 'w',
		'value_d': 'w',
			},

		4: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': '',
		'value_c': 'w',
		'value_d': 'w',
			},

		5: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': '',
		'value_c': 'w',
		'value_d': 'w',
			},

		6: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		7: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		8: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		9: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		10: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		11: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		12: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		13: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		14: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		15: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		16: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		17: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		18: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		19: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		20: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		21: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		22: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		23: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		24: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		25: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		26: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		27: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		28: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		29: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		30: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		31: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		32: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		33: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		34: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		35: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		36: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		37: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		38: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		39: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		40: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		41: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		42: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		43: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		44: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		45: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		46: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		47: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		48: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		49: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		50: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		51: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		52: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		53: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		54: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		55: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		56: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		57: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		58: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		59: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},
		60: {'question': "",
		'answer_a': '',
		'answer_b': '',
		'answer_c': '',
		'answer_d': '',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},


				},

	}

long_term_care_10_final_results = {
	"title": "Florida Discount Continuing Education: Long-Term-Care Final Results",
	"url_pass": "health_course_2_course_complete",
	"url_fail": 'health_course_2_final_prep',
	"answers": {
		1: '',
		2: '',
		3: '',
		4: '',
		5: '',
		6: '',
		7: '',
		8: '',
		9: '',
		10: '',
		11: '',
		12: '',
		13: '',
		14: '',
		15: '',
		16: '',
		17: '',
		18: '',
		19: '',
		20: '',
		21: '',
		22: '',
		23: '',
		24: '',
		25: '',
		26: '',
		27: '',
		28: '',
		29: '',
		30: '',
		31: ' ',
		32: '',
		33: '',
		34: '',
		35: '',
		36: '',
		37: '',
		38: '',
		39: '',
		40: '',
		41: '',
		42: '',
		43: '',
		44: '',
		45: '',
		46: '',
		47: '',
		48: '',
		49: '',
		50: '',
		51: '',
		52: '',
		53: '',
		54: '',
		55: '',
		56: '',
		57: '',
		58: '',
		59: '',
		60: '',

			},

				}
