insurance_claims_5_intro = {
	# "session['course']": "life-health-course-4",
	"title": "Insurance Claims: Introduction",
	"course": "5-Hour Insurance Claims Update",
	"course_number": "113621",
	"hours_approved": "5 Life / Health / Annuity Agent Electives (2-15 & 2-18)",
	"price": "$9.50",
	"tagline": "This course fulfills the state-mandated requirements for the Life / Health / Annuity Agent Electives continuing education component for Florida-licensed agents.(2-15 & 2-18)",
	"summary": "In this course we will review the fundamental concepts and the complex coverage details involving Insurance Claims.",

	"highlight": {
		1: 'Overview of Company Operations and Insurance Fundamentals',
		2: 'Legal Concepts Related to Claims',
		3: 'Claims Investigation Techniques and Tools',
		4: 'Claims Handling Procedures',
		5: 'Innovations and Advancements in Claims Handling Practices',
		}
	}

insurance_claims_5_chapter_1 = {
	"title": "Insurance Claims: Chapter 1",
	"course": "5-Hour Insurance Claims",
	"chapter_no": 1,
	"chapter_total":  5,
	"pdf": "/static/fl-life-health/course-4-image/chapter-1.pdf",
	"url_results": "life_health_course_4_chapter_1_results",
	"question_1":"Any conscious action (or decision not to act) that \
	identifies and reduces the frequency, severity, or unpredictability of loss claims?",
	"answer_1a": "Insuring Claimant’s Rights",
	"answer_1b": "Risk Management",
	"answer_1c": "Appraising Damages",
	"answer_1d": "Adjusting Claims",
	"value_1a": "",
	"value_1b": "correct",
	"value_1c": "",
	"value_1d": "",
	"question_2":"When identifying possible risk exposures, \
	risk management professional must be able to do which of the following?",
	"answer_2a": "Test the significance of these actual loss exposures by the degree to which they may occur and disclose to clients the possible results and remedies",
	"answer_2b": "Employ proper methods for identifying those specific loss exposures that particular persons or organization faces at a particular time",
	"answer_2c": "Apply a logical classification scheme for identifying all possible exposures to loss",
	"answer_2d": "All of the above",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "correct",
	"result_title": "Insurance Claims: Chapter 1 Results",
	"answer_1": "Risk Management",
	"answer_2": "All of the above",
	"url_wrong": "life_health_course_4_chapter_1",
	"url_correct": "life_health_course_4_chapter_2",
	}

insurance_claims_5_chapter_2 = {
	"title": "Insurance Claims: Chapter 2",
	"course": "5-Hour Insurance Claims",
	"chapter_no": 2,
	"chapter_total":  5,
	"pdf": "/static/fl-life-health/course-4-image/chapter-2.pdf",
	"url_results": "life_health_course_4_chapter_2_results",
	"question_1":"What are the two types of insurance com­panies?",
	"answer_1a": "Mutual insurance company & Stock insurance company",
	"answer_1b": "Public insurance company & Private insuranc­e company",
	"answer_1c": "Mutual insurance company & Medical insurance company",
	"answer_1d": "Public insurance company & Stock insurance company ",
	"value_1a": "correct",
	"value_1b": "",
	"value_1c": "",
	"value_1d": "",
	"question_2":"Which department within a Claims Division of a large insurance carrier\
supervises adjusters?",
	"answer_2a": "Corporate claims office",
	"answer_2b": "Branch claims office",
	"answer_2c": "Regional claims office",
	"answer_2d": "National claims office",
	"value_2a": "",
	"value_2b": "correct",
	"value_2c": "",
	"value_2d": "",
	"result_title": "Insurance Claims: Chapter 2 Results",
	"answer_1": "Mutual insurance company & Stock insurance company",
	"answer_2": "Branch claims office",
	"url_wrong": "life_health_course_4_chapter_2",
	"url_correct": "life_health_course_4_chapter_3",
	}

insurance_claims_5_chapter_3 = {
	"title": "Insurance Claims: Chapter 3",
	"course": "5-Hour Insurance Claims",
	"chapter_no": 3,
	"chapter_total":  5,
	"pdf": "/static/fl-life-health/course-4-image/chapter-3.pdf",
	"url_results": "life_health_course_4_chapter_3_results",
	"question_1":"What should every good investigator strive to uncover?",
	"answer_1a": "Evidence and valid facts",
	"answer_1b": "Opinions and pictures",
	"answer_1c": "Monies owed to claimants",
	"answer_1d": "All of the above",
	"value_1a": "correct",
	"value_1b": "",
	"value_1c": "",
	"value_1d": "",
	"question_2":"Property upon which the total value has been paid as a result of a claim under an insurance policy is known as what?",
	"answer_2a": "Garbage",
	"answer_2b": "Appraisal Property",
	"answer_2c": "Junk market material",
	"answer_2d": "Salvage",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "correct",
	"result_title": "Insurance Claims: Chapter 3 Results",
	"answer_1": "Evidence and valid facts",
	"answer_2": "Salvage",
	"url_wrong": "life_health_course_4_chapter_3",
	"url_correct": "life_health_course_4_chapter_4",
	}

insurance_claims_5_chapter_4 = {
	"title": "Insurance Claims: Chapter 4",
	"course": "5-Hour Insurance Claims",
	"chapter_no": 4,
	"chapter_total":  5,
	"pdf": "/static/fl-life-health/course-4-image/chapter-4.pdf",
	"url_results": "life_health_course_4_chapter_4_results",
	"question_1":"What is the primary reason a professional is sued?",
	"answer_1a": "Lying",
	"answer_1b": "Unethical practices",
	"answer_1c": "Cost reduction through automation",
	"answer_1d": "Negligence",
	"value_1a": "",
	"value_1b": "",
	"value_1c": "",
	"value_1d": "correct",
	"question_2":"An insurance term referring to the event that activates coverage under the policy is called:",
	"answer_2a": "Policy activator",
	"answer_2b": "Claims processor",
	"answer_2c": "Policy trigger",
	"answer_2d": "Coverage event",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "correct",
	"value_2d": "",
	"result_title": "Insurance Claims: Chapter 4 Results",
	"answer_1": "Negligence",
	"answer_2": "Policy trigger",
	"url_wrong": "life_health_course_4_chapter_4",
	"url_correct": "life_health_course_4_chapter_5",
	}

insurance_claims_5_chapter_5 = {
	"title": "Insurance Claims: Chapter 5",
	"course": "5-Hour Insurance Claims",
	"chapter_no": 5,
	"chapter_total":  5,
	"pdf": "/static/fl-life-health/course-4-image/chapter-5.pdf",
	"url_results": "life_health_course_4_chapter_5_results",
	"question_1":"Which is not a good habit for responsible claims management?",
	"answer_1a": "Keep the insured client advised",
	"answer_1b": "Explore the possibility of settlement",
	"answer_1c": "Focusing on your fees",
	"answer_1d": "Consider the insured’s interest",
	"value_1a": "",
	"value_1b": "",
	"value_1c": "correct",
	"value_1d": "",
	"question_2":"How does technology make managing claims better?",
	"answer_2a": "Electronic and web claims processing",
	"answer_2b": "Improvement in insurer “legacy” computers",
	"answer_2c": "Cost reduction through automation",
	"answer_2d": "All of the above",
	"value_2a": "",
	"value_2b": "",
	"value_2c": "",
	"value_2d": "correct",
	"result_title": "Insurance Claims: Chapter 5 Results",
	"answer_1": "Focusing on your fees",
	"answer_2": "All of the above",
	"url_wrong": "life_health_course_4_chapter_5",
	"url_correct": "security_question",
	'url':'life_health_course_4_final_prep',
	'last_chapter':True,
	}

insurance_claims_5_final_prep = {
	"title": "Florida Discount Continuing Education: Insurance Claims Final Prep",
	"course": "5-Hour Insurance Claims Update",
	"url_final_exam":"life_health_course_4_final_exam",
	"url_review":"life_health_course_4_review",
	}

insurance_claims_5_review = {
	"title": "Florida Discount Continuing Education: Insurance Claims Review",
	"url_final_prep": "life_health_course_4_final_prep",
	"pdf": "/static/fl-life-health/course-4-image/full-course.pdf",
	}

insurance_claims_5_final_exam = {
	"title": "Florida Discount Continuing Education: Insurance Claims Final",
	"course": "5-Hour Insurance Claims Update",
	"url_final_results": "life_health_course_4_final_results",

	"questions": {
		1: {'question': "Under this type of coverage, a carrier will pay replacement cost instead\
		 of actual cash value for lost or damaged property?",
		'answer_a': 'Propert value',
		'answer_b': 'Actual cash value',
		'answer_c': 'Replacement cost coverage',
		'answer_d': 'Damage control coverage',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		2: {'question': "What would happen if an insured had intentionally concealed or misrepresented any material fact or circumstance?",
		'answer_a': 'The part of the policy misrepresented will be void',
		'answer_b': 'The entire policy will be void ',
		'answer_c': 'Deductibles will increase',
		'answer_d': 'They will pay a penalty',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		3: {'question': "What does notification of a loss to an insurance company by a policyholder or a third person constitute?",
		'answer_a': 'An Adjustment',
		'answer_b': 'A Payout',
		'answer_c': 'An Appraisal',
		'answer_d': 'A Claim',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		4: {'question': "What policies extend coverage for liability for activities that occur over a policy year, \
		notwithstanding the fact that a suit might be brought at a later date to determine liability on the part of a carrier?",
		'answer_a': 'Occurrence coverage',
		'answer_b': 'Risk coverage',
		'answer_c': 'Appraisal coverage',
		'answer_d': 'Private coverage',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		5: {'question': "The person who is protected against loss and may or may not be the owner of the insurance policy is?",
		'answer_a': 'The Owner',
		'answer_b': 'The Insured',
		'answer_c': 'The Appraiser',
		'answer_d': 'The Underwriter',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		6: {'question': "New standards introduced in September 1996 require property owners who are selling or renting real estate built prior to____ to disclose any known lead-based paint or lead hazards.",
		'answer_a': '1988',
		'answer_b': '1977',
		'answer_c': '1999',
		'answer_d': '2001',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		7: {'question': "The company that extends insurance coverage over the subject matter by the sale of a contract known as an insurance policy is called what?",
		'answer_a': 'Issuer',
		'answer_b': 'Assister',
		'answer_c': 'Underwriter',
		'answer_d': 'writer',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		8: {'question': "What do you call the first peril in a chain of events without which a loss would not have been sustained?",
		'answer_a': 'Benefit cause',
		'answer_b': 'Secondary cause',
		'answer_c': 'Shared cause',
		'answer_d': 'Proximate cause',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		9: {'question': "Which insurance policies are defined as an insurance policy that provides coverage only if a claim is made during the policy period?",
		'answer_a': 'Occurence policy',
		'answer_b': 'Claims-made policy',
		'answer_c': 'Event policy',
		'answer_d': 'Trigger policy',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		10: {'question': "In an insurance policy, the relative obligations and responsibilities of both the carrier and the policyholder is called what?",
		'answer_a': 'The Declaration Page',
		'answer_b': 'The Deductible',
		'answer_c': 'The Insurance Agreement',
		'answer_d': 'Cancellation',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		11: {'question': "This occurs when there is damage to the property or health of a person other than the insured:",
		'answer_a': 'A “first-party loss”',
		'answer_b': 'A “second-party loss”',
		'answer_c': 'A “third-party loss”',
		'answer_d': 'A “fourth-party loss”',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		12: {'question': "Which policiy provide insurance coverage against liability for any claims that are presented to an insurance carrier\
		 during a policy year, regardless of when the underlying conduct giving rise to the liability occurred?",
		'answer_a': 'Non-Occurence policy',
		'answer_b': 'Plan A policy',
		'answer_c': 'Occurence policy',
		'answer_d': 'Claims-made policy',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		13: {'question': "Which is not one of the habits for responsible claims management?",
		'answer_a': 'Keep the insured client advised',
		'answer_b': 'Listen to the advice of defense counsel',
		'answer_c': 'Do not deplete the policy carelessly when there are multiple claims',
		'answer_d': 'Do not explore the possibility of settlement ',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		14: {'question': "Which is one of the four corporate divisions of most insurance companies?",
		'answer_a': 'Underwriting',
		'answer_b': 'Finance',
		'answer_c': 'Claims',
		'answer_d': 'All of the above',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		15: {'question': "What is the provision called that each carrier will pay a fair proportion of a loss when there is more than one policy in effect for the same property?",
		'answer_a': 'Pro rata contributions',
		'answer_b': 'The Insurance Agreement',
		'answer_c': 'Cancellation',
		'answer_d': 'Property & Casualty',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		16: {'question': "Who is the ultimate interpreter of an insurance policy?",
		'answer_a': 'Courts',
		'answer_b': 'Policyholder',
		'answer_c': 'Attorney',
		'answer_d': 'Carrier',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		17: {'question': "Which party could be involved in an insurance claim?",
		'answer_a': 'Mediator',
		'answer_b': 'Arbitrator',
		'answer_c': 'Lawyer',
		'answer_d': 'All of the above',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		18: {'question': "What is not an element of a valid claim?",
		'answer_a': 'Losses must be fortuitous',
		'answer_b': 'A loss must be sustained ',
		'answer_c': 'Losses can be intentionally caused by the policyholder ',
		'answer_d': 'Losses must be occasioned by an extraneous factor',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		19: {'question': "Generally, the burden of proving the existence of a loss is upon whom?",
		'answer_a': 'Policyholder',
		'answer_b': 'Insurer',
		'answer_c': 'Mediator',
		'answer_d': 'Injured',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		20: {'question': "In a claim involving death due to an accident, what  statute may apply where a surviving spouse,\
		 parents or children of the deceased may recover damages from the party responsible for the death?",
		'answer_a': 'Accidental deceased statute',
		'answer_b': 'Wrongful death statute',
		'answer_c': 'Next of kin statute',
		'answer_d': 'Survivors law',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		21: {'question': "If language in an insurance  policy is capable of being interpreted in two different ways, who will the courts favor?",
		'answer_a': 'Attorneys',
		'answer_b': 'Insurers',
		'answer_c': 'Adjusters',
		'answer_d': 'Policyholders',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		22: {'question': "Which is not one of the unfair claims practices in the Model Unfair Claim Settlement Practices Act?",
		'answer_a': 'Failing to adopt and maintain sound criteria for the investigation and processing of claims',
		'answer_b': 'Acting promptly upon notification of a claim arising under a policy',
		'answer_c': 'Misstating policy terms or relevant facts that affect coverage',
		'answer_d': 'Misrepresenting the statute of limitations',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		23: {'question': "Insurers claim to be losing how much a year to fraud?",
		'answer_a': '$15 - $20 billion',
		'answer_b': '$85 - $120 billion',
		'answer_c': '$85 - $120 million',
		'answer_d': '$15 - $20 million',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		24: {'question': "Many claim experts feel that the first_____ following a loss  is the time when losses can be minimized and excess claims and client dissatisfaction avoided. ",
		'answer_a': '48 hours',
		'answer_b': '1 week',
		'answer_c': '2 weeks',
		'answer_d': '1 month',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		25: {'question': "What constitutes an equitable insurance practice under the Insurance Consumer’s Bill of Rights and Responsibilities?",
		'answer_a': 'The right to a voice',
		'answer_b': 'The right to safeguards',
		'answer_c': 'The right to a remedy',
		'answer_d': 'All of the above',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		26: {'question': "Declares that the only modifications to the policy that are acceptable to a carrier are those that are in writing and attached to the policy as an endorsement:",
		'answer_a': 'Additions',
		'answer_b': 'Addendums',
		'answer_c': 'Amendments',
		'answer_d': 'Waivers',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'correct',
			},

		27: {'question': "A professional, trained in the examination, evaluation, and dispensation of claims is called:",
		'answer_a': 'An Appealer',
		'answer_b': 'An Underwriter',
		'answer_c': 'An Adjuster',
		'answer_d': 'An Appraiser',
		'value_a': 'w',
		'value_b': 'w',
		'value_c': 'correct',
		'value_d': 'w',
			},

		28: {'question': "The rights of a carrier to legally recoup the amount of settlement from a third party who is responsible for a loss after payment of a claim is called:",
		'answer_a': 'Subrogation',
		'answer_b': 'Cancellation',
		'answer_c': 'Obligation',
		'answer_d': 'Adjustment',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},

		29: {'question': "What are periodic payments made during the term of an insurance policy by an owner to the issuer for insuring against a loss called?",
		'answer_a': 'Deductibles',
		'answer_b': 'Premiums',
		'answer_c': 'Appraisals',
		'answer_d': 'Interest',
		'value_a': 'w',
		'value_b': 'correct',
		'value_c': 'w',
		'value_d': 'w',
			},

		30: {'question': "An _____ is one in which the insured has liability coverage only for injury or damage that occurs during the actual policy term.",
		'answer_a': 'Occurence policy',
		'answer_b': 'Claims-made policy ',
		'answer_c': 'Event policy',
		'answer_d': 'Trigger policy',
		'value_a': 'correct',
		'value_b': 'w',
		'value_c': 'w',
		'value_d': 'w',
			},


				},

	}


insurance_claims_5_final_results = {
	"title": "Florida Discount Continuing Education: Insurance Claims Final Results",
	"url_pass": "life_health_course_4_course_complete",
	"url_fail": 'life_health_course_4_final_prep',
	"answers": {
		1: 'Replacement cost coverage',
		2: 'The entire policy will be void',
		3: 'A Claim',
		4: 'Occurrence coverage',
		5: 'The Insured',
		6: '1977',
		7: 'Issuer',
		8: 'Proximate cause',
		9: 'Claims-made policy',
		10: 'The Insurance Agreement',
		11: 'A “third-party loss” ',
		12: 'Claims-made policy ',
		13: 'Do not explore the possibility of settlement',
		14: 'All of the above',
		15: 'Pro Rata Contributions',
		16: 'Courts',
		17: 'All of the above',
		18: 'Losses can be intentionally caused by the policyholder ',
		19: 'Policyholder',
		20: 'Wrongful death statute',
		21: 'Policyholders',
		22: 'Acting promptly upon notification of a claim arising under a policy',
		23: '$85 - $120 billion',
		24: '48 hours',
		25: 'All of the above',
		26: 'Waivers',
		27: 'An Adjuster',
		28: 'Subrogation',
		29: 'Premiums',
		30: 'Occurrence policy',

			},

				}
